####
# ATENTION:
# Replace all occurences of projeto with your project's name
####

# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  projeto-mysql-data:
    driver: local

  # Redis Data
  projeto-redis-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: projeto-mysql
    volumes:
      - projeto-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=projeto
      - MYSQL_DATABASE=projeto
      - MYSQL_USER=projeto
      - MYSQL_PASSWORD=projeto

  # Redis
  cache:
    image: redis:4.0
    container_name: projeto-redis
    command: --appendonly yes
    volumes:
      - projeto-redis-data:/data
    ports:
      - "6379:6379"

  # PHP (with Nginx)
  # you can change from nginx to apache, just change session 'image'
  app:
    image: ambientum/php:7.2-nginx
    container_name: projeto-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql
      - cache

      
